services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports: 
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskmanagement
    volumes:
      - mysql_data:/var/lib/mysql
      
  app:
    build: .
    image: task-management-app
    container_name: task-management-app
    ports: 
      - "8085:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/taskmanagement
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    
volumes:
  mysql_data: